local object = {}

-- Civilization Advances
-- recommended key prefix 'a'
--
object.aAdvancedFlight=civ.getTech(0)
object.aBasicLiteracy=civ.getTech(1)
object.aAmphibiousWarfare=civ.getTech(2)
object.aArmourPlate=civ.getTech(3)
object.aAerialGunnery=civ.getTech(4)
object.aAmericanScience=civ.getTech(5)
object.aBanking=civ.getTech(6)
object.aConstruction=civ.getTech(7)
object.aColonialTroops=civ.getTech(8)
object.aTheNationState=civ.getTech(9)
object.aChemistry=civ.getTech(10)
object.aChivalry=civ.getTech(11)
object.aLegalism=civ.getTech(12)
object.aArmsIndustry=civ.getTech(13)
object.aCombustion=civ.getTech(14)
object.aImperialism=civ.getTech(15)
object.aRadioTelegraphy=civ.getTech(16)
object.aNationalism=civ.getTech(17)
object.aFortressDesign=civ.getTech(18)
object.aStateSubsidies=civ.getTech(19)
object.aInternationalTrade=civ.getTech(20)
object.aDemocracy=civ.getTech(21)
object.aEconomics=civ.getTech(22)
object.aElectricity=civ.getTech(23)
object.aAmericanCulture=civ.getTech(24)
object.aEngineering=civ.getTech(25)
object.aOilIndustry=civ.getTech(26)
object.aEfficiency=civ.getTech(27)
object.aExplosives=civ.getTech(28)
object.aIndustrialization=civ.getTech(29)
object.aPoweredFlight=civ.getTech(30)
object.aAutocracy=civ.getTech(31)
object.aIronclads=civ.getTech(32)
object.aSocialDarwinism=civ.getTech(33)
object.aGuerrillaWarfare=civ.getTech(34)
object.aConscription=civ.getTech(35)
object.aCavalryWarfare=civ.getTech(36)
object.aAsianCulture=civ.getTech(37)
object.aEuropeanCulture=civ.getTech(38)
object.aTankDesign=civ.getTech(39)
object.aLaborUnion=civ.getTech(40)
object.aCivilService=civ.getTech(41)
object.aGeneralStaffs=civ.getTech(42)
object.aCulturalLiteracy=civ.getTech(43)
object.aMachineTools=civ.getTech(44)
object.aBattlecruisers=civ.getTech(45)
object.aAfricanExploration=civ.getTech(46)
object.aCrucibleProcess=civ.getTech(47)
object.aMassProduction=civ.getTech(48)
object.aBallistics=civ.getTech(49)
object.aMedicine=civ.getTech(50)
object.aMilIndComplex=civ.getTech(51)
object.aSocialism=civ.getTech(52)
object.aModernInfantry=civ.getTech(53)
object.aMonarchy=civ.getTech(54)
object.aPopularCulture=civ.getTech(55)
object.aInvention=civ.getTech(56)
object.aSteamWarships=civ.getTech(57)
object.aSteelAlloys=civ.getTech(58)
object.aSteamTurbines=civ.getTech(59)
object.aEuropeanScience=civ.getTech(60)
object.aBombers=civ.getTech(61)
object.aRubberExtraction=civ.getTech(62)
object.aCentralBanks=civ.getTech(63)
object.aPublicUtilities=civ.getTech(64)
object.aLandReform=civ.getTech(65)
object.aAirparks=civ.getTech(66)
object.aMassTransit=civ.getTech(67)
object.aImprovedBombers=civ.getTech(68)
object.aRefining=civ.getTech(69)
object.aFertilizers=civ.getTech(70)
object.aTheRepublic=civ.getTech(71)
object.aOperations=civ.getTech(72)
object.aNavalTorpedos=civ.getTech(73)
object.aSanitation=civ.getTech(74)
object.aSeaPower=civ.getTech(75)
object.aMilitarism=civ.getTech(76)
object.aModernFighters=civ.getTech(77)
object.aSteamEngine=civ.getTech(78)
object.aSteel=civ.getTech(79)
object.aRailroad=civ.getTech(80)
object.aTactics=civ.getTech(81)
object.aReligion=civ.getTech(82)
object.aAeronautics=civ.getTech(83)
object.aRegionalTrade=civ.getTech(84)
object.aUniversity=civ.getTech(85)
object.aMotorisedWarfare=civ.getTech(86)
object.aRifledArtillery=civ.getTech(87)
object.aLiteracy=civ.getTech(88)
object.aThe20thCentury=civ.getTech(89)
object.aLargeCalibreGuns=civ.getTech(90)
object.aMassiveArtillery=civ.getTech(91)
object.aImprovedTanks=civ.getTech(92)
object.aSteelWarships=civ.getTech(93)
object.aPreDreadnoughts=civ.getTech(94)
object.aDreadnoughts=civ.getTech(95)
object.aNavalism=civ.getTech(96)
object.aSubmarines=civ.getTech(97)
object.aNavalAirArm=civ.getTech(98)
object.aColonialism=civ.getTech(99)

-- Map Locations (tiles/squares)
-- recommended key prefix 'l'

--object.lTopLeft                 = civ.getTile(0,0,0)
--object.lRome                    = civ.getTile(72,34,0)


-- Cities
-- recommended key prefix 'c'
-- It is not recommended to put cities into this list if the city
-- can be destroyed. This list returns an error if 'nil' is the value
-- associated with the key (see bottom of file), so that could cause
-- a problem if a city in this list is destroyed.  Also, if another
-- city is founded, the ID number of the city might get reused, causing
-- more confusion.  An alternate way to reference a city is by using
-- object.lRome.city when you actually need the city (and suitably guarding
-- against nil values)

--object.cRome                    = civ.getCity(0)

-- Unit Types
-- recommended key prefix 'u'
object.uLaborers=civ.getUnitType(0)
object.uEngineers=civ.getUnitType(1)
object.uTribalCamp=civ.getUnitType(2)
object.uTribalRifles=civ.getUnitType(3)
object.uNativeRifles=civ.getUnitType(4)
object.uBandits=civ.getUnitType(5)
object.uMilitia=civ.getUnitType(6)
object.uNativeUprising=civ.getUnitType(7)
object.uEliteGuards=civ.getUnitType(8)
object.uIrregulars=civ.getUnitType(9)
object.uHighlanders1=civ.getUnitType(10)
object.uRiflemen1=civ.getUnitType(11)
object.uMarines=civ.getUnitType(12)
object.uGurkhas=civ.getUnitType(13)
object.uRiflemen2=civ.getUnitType(14)
object.uRiflemen3=civ.getUnitType(15)
object.uGrenadiers1=civ.getUnitType(16)
object.uGrenadiers2=civ.getUnitType(17)
object.uGrenadiers3=civ.getUnitType(18)
object.uTribalCapital=civ.getUnitType(19)
object.uZouaves=civ.getUnitType(20)
object.uVoltigeurs=civ.getUnitType(21)
object.uInfantrie1=civ.getUnitType(22)
object.uInfantrie2=civ.getUnitType(23)
object.uInfantry=civ.getUnitType(24)
object.uGuards1=civ.getUnitType(25)
object.uGuards2=civ.getUnitType(26)
object.uImperialTroops=civ.getUnitType(27)
object.uImperialArmy1=civ.getUnitType(28)
object.uImperialArmy2=civ.getUnitType(29)
object.uUSTroops=civ.getUnitType(30)
object.uUSArmy1=civ.getUnitType(31)
object.uUSArmy2=civ.getUnitType(32)
object.uWarParty=civ.getUnitType(33)
object.uTribalHorse=civ.getUnitType(34)
object.uNativeHorse=civ.getUnitType(35)
object.uBoerKommando=civ.getUnitType(36)
object.uCavalry=civ.getUnitType(37)
object.uSepoys=civ.getUnitType(38)
object.uUhlans=civ.getUnitType(39)
object.uChasseurs=civ.getUnitType(40)
object.uCossacks=civ.getUnitType(41)
object.uNihonCavalry=civ.getUnitType(42)
object.uUSCavalry=civ.getUnitType(43)
object.uMotorisedInf=civ.getUnitType(44)
object.uTank=civ.getUnitType(45)
object.uLightTank=civ.getUnitType(46)
object.uAgent=civ.getUnitType(47)
object.uMfgGoods=civ.getUnitType(48)
object.uGoodsTruck=civ.getUnitType(49)
object.uMachineGuns=civ.getUnitType(50)
object.uCannons=civ.getUnitType(51)
object.uRifledGun=civ.getUnitType(52)
object.uLightArtillery=civ.getUnitType(53)
object.uFieldArtillery=civ.getUnitType(54)
object.uHeavyArtillery=civ.getUnitType(55)
object.uTrackedGun=civ.getUnitType(56)
object.uRailwayGun=civ.getUnitType(57)
object.uExpedition=civ.getUnitType(58)
object.uMonoplane=civ.getUnitType(59)
object.uBiplane=civ.getUnitType(60)
object.uFighter=civ.getUnitType(61)
object.uBomber1=civ.getUnitType(62)
object.uBomber2=civ.getUnitType(63)
object.uAirship=civ.getUnitType(64)
object.uSteamYacht=civ.getUnitType(65)
object.uFreighter=civ.getUnitType(66)
object.uOceanLiner=civ.getUnitType(67)
object.uGunboat=civ.getUnitType(68)
object.uIronclad=civ.getUnitType(69)
object.uSteamFrigate=civ.getUnitType(70)
object.uSteamWarship=civ.getUnitType(71)
object.uLightCruiser=civ.getUnitType(72)
object.uBattleship=civ.getUnitType(73)
object.uDestroyers=civ.getUnitType(74)
object.uArmoredCruiser=civ.getUnitType(75)
object.uDreadnought=civ.getUnitType(76)
object.uBattlecruiser=civ.getUnitType(77)
object.uCarrier=civ.getUnitType(78)
object.uSubmarine=civ.getUnitType(79)
object.uUBoat=civ.getUnitType(80)
object.uAborigines=civ.getUnitType(81)
object.uTribalWarriors=civ.getUnitType(82)
object.uRebelRifles=civ.getUnitType(83)
object.uNativeArmy=civ.getUnitType(84)
object.uMalayRifles=civ.getUnitType(85)
object.uMaasaiWarriors=civ.getUnitType(86)
object.uAnarchists=civ.getUnitType(87)
object.uTatars=civ.getUnitType(88)
object.uHighlanders2=civ.getUnitType(89)
object.uTurkishArmy=civ.getUnitType(90)
object.uChineseArmy=civ.getUnitType(91)
object.uIndianRebels=civ.getUnitType(92)
object.uEthiopianArmy=civ.getUnitType(93)
object.uBerbers=civ.getUnitType(94)
object.uBalkanRebels=civ.getUnitType(95)
object.uArgentineArmy=civ.getUnitType(96)
object.uBolsheviks=civ.getUnitType(97)

-- City Improvements
-- recommended key prefix 'i'
--          
object.iNothing=civ.getImprovement(0)
object.iCapital=civ.getImprovement(1)
object.iArmyCamp=civ.getImprovement(2)
object.iWarehouses=civ.getImprovement(3)
object.iColonialPolice=civ.getImprovement(4)
object.iBank=civ.getImprovement(5)
object.iSchool=civ.getImprovement(6)
object.iMagistrate=civ.getImprovement(7)
object.iFortifications=civ.getImprovement(8)
object.iModernSewer=civ.getImprovement(9)
object.iLocalIndustry=civ.getImprovement(10)
object.iStadium=civ.getImprovement(11)
object.iUniversity=civ.getImprovement(12)
object.iNone=civ.getImprovement(13)
object.iMusicHall=civ.getImprovement(14)
object.iFactory=civ.getImprovement(15)
object.iIndustrialComplex=civ.getImprovement(16)
--object.iNone=civ.getImprovement(17)
--object.iNone=civ.getImprovement(18)
object.iSteelMill=civ.getImprovement(19)
object.iRefinery=civ.getImprovement(20)
--object.iNone=civ.getImprovement(21)
object.iCommercialExchange=civ.getImprovement(22)
object.iModernHousing=civ.getImprovement(23)
object.iIntensiveAgriculture=civ.getImprovement(24)
object.iGrandRailwayStation=civ.getImprovement(25)
object.iLaboratory=civ.getImprovement(26)
object.iAntiAircraftDefences=civ.getImprovement(27)
object.iCoastalBattery=civ.getImprovement(28)
--object.iNone=civ.getImprovement(29)
object.iHarbour=civ.getImprovement(30)
object.iWorldPort=civ.getImprovement(31)
object.iAirpark=civ.getImprovement(32)
object.iPoliceHQ=civ.getImprovement(33)
object.iCoalingStation=civ.getImprovement(34)
object.iTransporter=civ.getImprovement(35)

-- Tribes
-- recommended key prefix 't'
--
object.tBarbarians              = civ.getTribe(0)
object.tWhiteTribe              = civ.getTribe(1)
object.tGreenTribe              = civ.getTribe(2)
object.tBlueTribe               = civ.getTribe(3)
object.tYellowTribe             = civ.getTribe(4)
object.tCyanTribe               = civ.getTribe(5)
object.tOrangeTribe             = civ.getTribe(6)
object.tPurpleTribe             = civ.getTribe(7)

-- Wonders
-- recommended key prefix 'w'
object.wUkrainianFarms=civ.getWonder(0)
object.wCasaRosada	=civ.getWonder(1)
object.wPanamaCanal=civ.getWonder(2)
object.wAdmiralty=civ.getWonder(3)
--object.wNone=civ.getWonder(4)
object.wHerrenhaus=civ.getWonder(5)
--object.wNone=civ.getWonder(6)
object.wMilitaryAcademy=civ.getWonder(7)
object.wWorkshopoftheWorld=civ.getWonder(8)
object.wDiplomaticCorps=civ.getWonder(9)
object.wFreeEnterprise=civ.getWonder(10)
object.wEcolePolytechnique=civ.getWonder(11)
--object.wNone=civ.getWonder(12)
object.wKremlin=civ.getWonder(13)
--object.wNone=civ.getWonder(14)
object.wPrussianNobility=civ.getWonder(15)
object.wRuhrChemicalIndustry=civ.getWonder(16)
object.wBritishEmpire=civ.getWonder(17)
object.wArmsRace=civ.getWonder(18)
object.wPalaceofVersailles=civ.getWonder(19)
object.wThirdRepublic=civ.getWonder(20)
object.wWomensSuffrage=civ.getWonder(21)
--object.wNone=civ.getWonder(22)
--object.wNone=civ.getWonder(23)
object.wImperialPowers=civ.getWonder(24)
--object.wNone=civ.getWonder(25)
object.wMeijiRestoration=civ.getWonder(26)
object.wParliament=civ.getWonder(27)

-- this will give you an if you try to access a key not entered into
-- the object table, which could be helpful for debugging, but it
-- means that no nil value can ever be returned for table object
-- If you need that ability, comment out this section
setmetatable(object,{__index = function(myTable,key)
    error("The object table doesn't have a value associated with "..tostring(key)..".") end})

return object
