local object = {}

-- Civilization Advances
-- recommended key prefix 'a'
--
object.aMilitiaSystem                = civ.getTech(0)
object.aEducation                    = civ.getTech(1)
object.aMaritimeLaw                  = civ.getTech(2)
object.aWoodWorking                  = civ.getTech(3)
object.aAgriculture                  = civ.getTech(4)
object.aSpecialTechnology            = civ.getTech(5)
object.aColonialGovernment           = civ.getTech(6)
object.aRoadConstruction             = civ.getTech(7)
object.aHorseBreeding                = civ.getTech(8)
object.aSpiritoftheManitou           = civ.getTech(9)
object.aRightofCoinage               = civ.getTech(10)
--object.a---------------------------=civ.getTech(11)
object.aShipbuilding                 = civ.getTech(12)
--object.a---------------------------=civ.getTech(13)
object.aMilitaryDrill                = civ.getTech(14)
--object.a---------------------------=civ.getTech(15)
object.aCavalryTactics               = civ.getTech(16)
--object.a---------------------------= civ.getTech(17)
----object.a-------------------------=civ.getTech(18)
object.aHygiene                      = civ.getTech(19)
object.aBankingSystem                = civ.getTech(20)
--object.a---------------------------=civ.getTech(21)
object.aPoetryandDrama               = civ.getTech(22)
object.aMercantilism                 = civ.getTech(23)
object.aSpecialTechnology            = civ.getTech(24)
object.aSiegeWeaponry                = civ.getTech(25)
object.aFluidMechanics               = civ.getTech(26)
object.aPhysics                      = civ.getTech(27)
--object.a---------------------------=civ.getTech(28)
object.aOverseaTrade                 = civ.getTech(29)
--object.a---------------------------=civ.getTech(30)
--object.a---------------------------=civ.getTech(31)
--object.a---------------------------=civ.getTech(32)
object.aCoastalDefence               = civ.getTech(33)
object.aPatriotism                   = civ.getTech(34)
--object.a---------------------------=civ.getTech(35)
object.aFinanceAct                   = civ.getTech(36)
object.aSpecialTechnology            = civ.getTech(37)
object.aSpecialTechnology            = civ.getTech(38)
object.aNavalWarfare                 = civ.getTech(39)
--object.a---------------------------=civ.getTech(40)
--object.a---------------------------=civ.getTech(41)
--object.a---------------------------=civ.getTech(42)
--object.a---------------------------=civ.getTech(43)
--object.a---------------------------=civ.getTech(44)
--object.a---------------------------=civ.getTech(45)
--object.a---------------------------=civ.getTech(46)
--object.a---------------------------=civ.getTech(47)
--object.a---------------------------=civ.getTech(48)
--object.a---------------------------=civ.getTech(49)
object.aMedicine                     = civ.getTech(50)
--object.a---------------------------=civ.getTech(51)
--object.a---------------------------=civ.getTech(52)
--object.a---------------------------=civgetTech(53)
--object.a---------------------------=civ.getTech(54)
object.aProtestantism                = civ.getTech(55)
object.aMythology                    = civ.getTech(56)
--object.a---------------------------=civ.getTech(57)
--object.a---------------------------=civ.getTech(58)
--object.a---------------------------=civ.getTech(59)
object.aSpecialTechnology            = civ.getTech(60)
--object.a---------------------------=civ.getTech(61)
--object.a---------------------------=civ.getTech(62)
--object.a---------------------------=civ.getTech(63)
object.aArchery                      = civ.getTech(64)
--object.a---------------------------=civ.getTech(65)
--object.a---------------------------=civ.getTech(66)
object.aRoadSystem                   =civ.getTech(67)
--object.a---------------------------=civ.getTech(68)
--object.a---------------------------=civ.getTech(69)
object.aThreeFieldSystem             =civ.getTech(70)
--object.a---------------------------=civ.getTech(71)
--object.a---------------------------=civ.getTech(72)
--object.a---------------------------=civ.getTech(73)
--object.a---------------------------=civ.getTech(74)
--object.a---------------------------=civ.getTech(75)
object.aAnimalHusbandry              = civ.getTech(76)
object.aHorsebackRiding              = civ.getTech(77)
object.aHunting                      =civ.getTech(78)
object.aMartialSocieties             =civ.getTech(79)
object.aReligiousSocieties           =civ.getTech(80)
object.aTribalReformation            =civ.getTech(81)
object.aReformedChurch               = civ.getTech(82)
--object.a---------------------------=civ.getTech(83)
object.aTradingRoutes                = civ.getTech(84)
object.aHigherEducation              = civ.getTech(85)
--object.a---------------------------=civ.getTech(86)
--object.a---------------------------=civ.getTech(86)
object.aPrintingPress                = civ.getTech(88)
object.aModernScience                = civ.getTech(89)
object.aMedievalAdministration       = civ.getTech(90)
object.aLibertyorDeath               = civ.getTech(91)
object.aRuleBritannia                = civ.getTech(92)
object.aTribalAllegiance             = civ.getTech(93)
--object.a---------------------------=civ.getTech(94)
--object.a---------------------------=civ.getTech(95)
--object.a---------------------------=civ.getTech(96)
--object.a---------------------------=civ.getTech(97)
--object.a---------------------------=civ.getTech(98)
--object.a---------------------------=civ.getTech(99)

-- Map Locations (tiles/squares)
-- recommended key prefix 'l'

--object.lTopLeft                 = civ.getTile(0,0,0)
--object.lRome                    = civ.getTile(72,34,0)


-- Cities
-- recommended key prefix 'c'
-- It is not recommended to put cities into this list if the city
-- can be destroyed. This list returns an error if 'nil' is the value
-- associated with the key (see bottom of file), so that could cause
-- a problem if a city in this list is destroyed.  Also, if another
-- city is founded, the ID number of the city might get reused, causing
-- more confusion.  An alternate way to reference a city is by using
-- object.lRome.city when you actually need the city (and suitably guarding
-- against nil values)
--object.cRome                    = civ.getCity(0)

-- Unit Types
-- recommended key prefix 'u'

object.uFarmer                        =civ.getUnitType(0)
object.uEngineers                     =civ.getUnitType(1)
object.uLightCorps                    =civ.getUnitType(2)
object.uLineInfantry                  =civ.getUnitType(3)
object.uRoyalMarines                  =civ.getUnitType(4)
object.uLineGrenadiers                =civ.getUnitType(5)
object.uHighlanderRegt                =civ.getUnitType(6)
--object.u----------------------------=civ.getUnitType(7)
object.uPirates                       =civ.getUnitType(8)
object.uMinutemen                     =civ.getUnitType(9)
object.uBritishLegion                 =civ.getUnitType(10)
object.uLoyalists                     =civ.getUnitType(11)
object.uCanadianLoyalists             =civ.getUnitType(12)
object.uQueensRangers                 =civ.getUnitType(13)
object.uDutchLineInfantry             =civ.getUnitType(14)
object.uFrenchFusiliers               =civ.getUnitType(15)
object.uFrenchGrenadiers              =civ.getUnitType(16)
object.uSpanishMusketeers             =civ.getUnitType(17)
object.uSpanishGrenadiers             =civ.getUnitType(18)
object.uFortress                      =civ.getUnitType(19)
object.uContinentalLightCorps         =civ.getUnitType(20)
object.uConnecticutLine               =civ.getUnitType(21)
object.uCitadel                       =civ.getUnitType(22)
object.uDelawareLine                  =civ.getUnitType(23)
object.uGeorgiaLine                   =civ.getUnitType(24)
object.uMassachusettsLine             =civ.getUnitType(25)
object.uMarylandLine                  =civ.getUnitType(26)
object.uNewHampshireLine              =civ.getUnitType(27)
object.uNewYorkLine                   =civ.getUnitType(28)
object.uNewJerseyLine                 =civ.getUnitType(29)
object.uNorthCarolinaLine             =civ.getUnitType(30)
object.uPennsylvaniaLine              =civ.getUnitType(31)
object.uRhodeIslandLine               =civ.getUnitType(32)
object.uSouthCarolinaLine             =civ.getUnitType(33)
object.uVirginiaLine                  =civ.getUnitType(34)
object.uContinentalRifles             =civ.getUnitType(35)
object.uMississippiRegt               =civ.getUnitType(36)
object.uLouisianaRegt                 =civ.getUnitType(37)
object.uFloridaRegt                   =civ.getUnitType(38)
object.uWarriorSociety                =civ.getUnitType(39)
object.uArchers                       =civ.getUnitType(40)
object.uTomahawkThrower               =civ.getUnitType(41)
object.uWarriors                      =civ.getUnitType(42)
object.uMusketmen                     =civ.getUnitType(43)
object.uEastIndiaCoRegt               =civ.getUnitType(44)
--object.u----------------------------=civ.getUnitType(45)
object.uNobleCitizen                  =civ.getUnitType(46)
object.uTrapper                       =civ.getUnitType(47)
object.uSupplyWagon                   =civ.getUnitType(48)
object.uMerchant                      =civ.getUnitType(49)
object.uLightDragoons                 =civ.getUnitType(50)
object.uQueensLightDragoons           =civ.getUnitType(51)
object.uMountedLoyalists              =civ.getUnitType(52)
object.uQueensHussars                 =civ.getUnitType(53)
object.uTarletonsDragoons             =civ.getUnitType(54)
object.uFieldArtillery                =civ.getUnitType(55)
object.uFieldHowitzer                 =civ.getUnitType(56)
object.uConnecticutDragoons           =civ.getUnitType(57)
object.uNewJerseyDragoons             =civ.getUnitType(58)
object.uNewYorkDragoons               =civ.getUnitType(59)
object.uPennsylvaniaDragoons          =civ.getUnitType(60)
object.uSouthCarolinaDragoons         =civ.getUnitType(61)
object.uGeorgiaDragoons               =civ.getUnitType(62)
object.uConnecticutArtillery          =civ.getUnitType(63)
object.uNewYorkArtillery              =civ.getUnitType(64)
object.uPennsylvaniaArtillery         =civ.getUnitType(65)
object.uRhodeIslandArtillery          =civ.getUnitType(66)
object.uFrenchHussars                 =civ.getUnitType(67)
object.uFrenchArtillery               =civ.getUnitType(68)
object.uSpanishDragoons               =civ.getUnitType(69)
object.uSpanishArtillery              =civ.getUnitType(70)
object.uHessianSappers                =civ.getUnitType(71)
object.uHessianLightCorps             =civ.getUnitType(72)
object.uHessianMusketeers             =civ.getUnitType(73)
object.uHessianGrenadiers             =civ.getUnitType(74)
object.uHessianJaegerRegt             =civ.getUnitType(75)
object.uHessianDragoons               =civ.getUnitType(76)
object.uHessianArtillery              =civ.getUnitType(77)
object.uTribesmen                     =civ.getUnitType(78)
object.uHorsemen                      =civ.getUnitType(79)
object.uMountedSpearmen               =civ.getUnitType(80)
object.uChiefsBodyguards              =civ.getUnitType(81)
object.uNewYorkLoyalists              =civ.getUnitType(82)
object.uNorthCarolinaLoyalists        =civ.getUnitType(83)
object.uPennsylvaniaLoyalists         =civ.getUnitType(84)
object.uIrishVolunteers               =civ.getUnitType(85)
object.uColouredTroops                =civ.getUnitType(86)
object.uEthiopianRegt                 =civ.getUnitType(87)
object.uRogersRangers                 =civ.getUnitType(88)
object.uNewfoundlandLoyalists         =civ.getUnitType(89)
object.uKingsAmericanRegt             =civ.getUnitType(90)
object.uCharlesCornwallis             =civ.getUnitType(91)
object.uWilliamHowe                   =civ.getUnitType(92)
object.uHenryClinton                  =civ.getUnitType(93)
object.uJohnBurgoyne                  =civ.getUnitType(94)
object.uBanastreTarleton              =civ.getUnitType(95)
object.uLordDunmore                   =civ.getUnitType(96)
object.uStockbridgeMohicans           =civ.getUnitType(97)
object.uGreenMountainBoys             =civ.getUnitType(98)
object.uMorgansRifles                 =civ.getUnitType(99)
object.uLeesLegion                    =civ.getUnitType(100)
object.uArmandsLegion                 =civ.getUnitType(101)
object.uGeorgeWashington              =civ.getUnitType(102)
object.uHoratioGates                  =civ.getUnitType(103)
object.uMarquisdeLaFayette            =civ.getUnitType(104)
object.uWilhelmvonSteuben             =civ.getUnitType(105)
object.uFootGuards                    =civ.getUnitType(106)
object.uIrishRegt                     =civ.getUnitType(107)
object.uRoyalWelshFusiliers           =civ.getUnitType(108)
object.uNewYorkLightCorps             =civ.getUnitType(109)
object.u1stPennsylvaniaRegt           =civ.getUnitType(110)
object.uLauzansLegion                 =civ.getUnitType(111)
object.uGatinoisRegt                  =civ.getUnitType(112)
object.uSaintongeRegt                 =civ.getUnitType(113)
object.uRoyalDeuxPontsRegt            =civ.getUnitType(114)
object.uComtedeRochambeau             =civ.getUnitType(115)
object.uWaldeckRegt                   =civ.getUnitType(116)
object.uvonKnyphausenRegt             =civ.getUnitType(117)
object.uvonRallsGrenadiersRegt        =civ.getUnitType(118)
object.uvonRallsGrenadierRegt         =civ.getUnitType(118)
object.uJohannRall                    =civ.getUnitType(119)
object.uEastIndiaman                  =civ.getUnitType(120)
object.uPrivateers                    =civ.getUnitType(121)
object.uFrigate                       =civ.getUnitType(122)
object.uShipoftheLine                 =civ.getUnitType(123)
object.uManofWar                      =civ.getUnitType(124)
object.uPirateShip                    =civ.getUnitType(125)
object.uCannonballs                   =civ.getUnitType(126)

-- City Improvements
-- recommended key prefix 'i'
--          
object.iNothing                        = civ.getImprovement(0)
object.iParliament                     = civ.getImprovement(1)
object.iMilitaryCamp                   = civ.getImprovement(2)
object.iFarm                           = civ.getImprovement(3)
object.iTotemPole                      = civ.getImprovement(4)
object.iMarketplace                    = civ.getImprovement(5)
object.iSchool                         = civ.getImprovement(6)
object.iTownHall                       = civ.getImprovement(7)
object.iFortifications                 = civ.getImprovement(8)
object.iSewerSystem                    = civ.getImprovement(9)
object.iBank                           = civ.getImprovement(10)
object.iChurch                         = civ.getImprovement(11)
object.iPublicLibrary                  = civ.getImprovement(12)
--object.i-----------------------------=civ.getImprovement(13)
object.iTheater                        = civ.getImprovement(14)
object.iManufacture                    = civ.getImprovement(15)
object.iCannonFoundry                  = civ.getImprovement(16)
--object.i-----------------------------=civ.getImprovement(17)
--object.i-----------------------------=civ.getImprovement(18)
--object.i-----------------------------=civ.getImprovement(19)
object.iSawmill                        = civ.getImprovement(20)
--object.i-----------------------------=civ.getImprovement(21)
object.iTradingCompany                 = civ.getImprovement(22)
object.iHospital                       = civ.getImprovement(23)
object.iGreatMarket                    = civ.getImprovement(24)
object.iCobbledRoads                   = civ.getImprovement(25)
object.iCollege                        = civ.getImprovement(26)
--object.i-----------------------------=civ.getImprovement(27)
object.iCoastalDefence                 = civ.getImprovement(28)
--object.i-----------------------------=civ.getImprovement(29)
object.iHarbor                         = civ.getImprovement(30)
object.iShipwright                     = civ.getImprovement(31)
--object.i-----------------------------=civ.getImprovement(32)
--object.i-----------------------------=civ.getImprovement(33)
object.iShipyard                       = civ.getImprovement(34)
--object.i-----------------------------=civ.getImprovement(35)

-- Tribes
-- recommended key prefix 't'
--
object.tBarbarians              = civ.getTribe(0)
object.tWhiteTribe              = civ.getTribe(1)
object.tGreenTribe              = civ.getTribe(2)
object.tBlueTribe               = civ.getTribe(3)
object.tYellowTribe             = civ.getTribe(4)
object.tCyanTribe               = civ.getTribe(5)
object.tOrangeTribe             = civ.getTribe(6)
object.tPurpleTribe             = civ.getTribe(7)

-- Wonders
-- recommended key prefix 'w'
--object.w------------------------------=civ.getWonder(0)
object.wOhioCompany                     = civ.getWonder(1)
object.wEastIndiaTradingCompany         = civ.getWonder(2)
--object.w------------------------------=civ.getWonder(3)
--object.w------------------------------=civ.getWonder(4)
object.wGreatManitou                    = civ.getWonder(5)
--object.w------------------------------=civ.getWonder(6)
object.wValleyForgeEncampment           =civ.getWonder(7)
object.wRoyalMilitaryAcademy            = civ.getWonder(8)
--object.w------------------------------=civ.getWonder(9)
object.wPalaceofVersailles              = civ.getWonder(10)
object.wHudsonsBayCompany               = civ.getWonder(11)
object.wRoyalNavalCollege               = civ.getWonder(12)
object.wBostonTeaParty                  = civ.getWonder(13)
--object.w------------------------------=civ.getWonder(14)
object.wLibertyBell                     = civ.getWonder(15)
object.wHarvardUniversity               = civ.getWonder(16)
--object.w------------------------------=civ.getWonder(17)
--object.w------------------------------=civ.getWonder(18)
--object.w------------------------------=civ.getWonder(19)
object.wHousesofParliament              = civ.getWonder(20)
object.wContinentalCongress             = civ.getWonder(21)
--object.w------------------------------=civ.getWonder(22)
--object.w------------------------------=civ.getWonder(23)
--object.w------------------------------=civ.getWonder(24)
--object.w------------------------------=civ.getWonder(25)
--object.w------------------------------=civ.getWonder(26)
object.wDeclarationofIndependence       = civ.getWonder(27)

-- this will give you an if you try to access a key not entered into
-- the object table, which could be helpful for debugging, but it
-- means that no nil value can ever be returned for table object
-- If you need that ability, comment out this section
setmetatable(object,{__index = function(myTable,key)
    error("The object table doesn't have a value associated with "..tostring(key)..".") end})

return object
