local object = {}

-- Civilization Advances
-- recommended key prefix 'a'
--
object.aAdvancedFligh           = civ.getTech(0)
object.aAlphabet                = civ.getTech(1)
object.aAmphibiousWarfare       = civ.getTech(2)
object.aAstronomy               = civ.getTech(3)
object.aAtomicTheory            = civ.getTech(4)
object.aAutomobile              = civ.getTech(5)
object.aBanking                 = civ.getTech(6)
object.aBridgeBuilding          = civ.getTech(7)
object.aBronzeWorking           = civ.getTech(8)
object.aCeremonialBurial        = civ.getTech(9)
object.aChemistry               = civ.getTech(10)
object.aChivalry                = civ.getTech(11)
object.aCodeofLaws              = civ.getTech(12)
object.aCombinedArms            = civ.getTech(13)
object.aCombustion              = civ.getTech(14)
object.aCommunism               = civ.getTech(15)
object.aComputers               = civ.getTech(16)
object.aConscription            = civ.getTech(17)
object.aConstruction            = civ.getTech(18)
object.aCorporation             = civ.getTech(19)
object.aCurrency                = civ.getTech(20)
object.aDemocracy               = civ.getTech(21)
object.aEconomics               = civ.getTech(22)
object.aElectricity             = civ.getTech(23)
object.aElectronics             = civ.getTech(24)
object.aEngineering             = civ.getTech(25)
object.aEnvironmentalism        = civ.getTech(26)
object.aEspionage               = civ.getTech(27)
object.aExplosives              = civ.getTech(28)
object.aFeudalism               = civ.getTech(29)
object.aFlight                  = civ.getTech(30)
object.aFundamentalism          = civ.getTech(31)
object.aFusionPower             = civ.getTech(32)
object.aGeneticEngineering      = civ.getTech(33)
object.aGuerrillaWarfare        = civ.getTech(34)
object.aGunpowder               = civ.getTech(35)
object.aHorsebackRiding         = civ.getTech(36)
object.aIndustrialization       = civ.getTech(37)
object.aInvention               = civ.getTech(38)
object.aIronWorking             = civ.getTech(39)
object.aLaborUnion              = civ.getTech(40)
object.aLaser                   = civ.getTech(41)
object.aLeadership              = civ.getTech(42)
object.aLiteracy                = civ.getTech(43)
object.aMachineTools            = civ.getTech(44)
object.aMagnetism               = civ.getTech(45)
object.aMapMaking               = civ.getTech(46)
object.aMasonry                 = civ.getTech(47)
object.aMassProduction          = civ.getTech(48)
object.aMathematics             = civ.getTech(49)
object.aMedicine                = civ.getTech(50)
object.aMetallurgy              = civ.getTech(51)
object.aMiniaturization         = civ.getTech(52)
object.aMobileWarfare           = civ.getTech(53)
object.aMonarchy                = civ.getTech(54)
object.aMonotheism              = civ.getTech(55)
object.aMysticism               = civ.getTech(56)
object.aNavigation              = civ.getTech(57)
object.aNuclearFission          = civ.getTech(58)
object.aNuclearPower            = civ.getTech(59)
object.aPhilosophy              = civ.getTech(60)
object.aPhysics                 = civ.getTech(61)
object.aPlastics                = civ.getTech(62)
object.aPlumbing                = civ.getTech(63)
object.aPolytheism              = civ.getTech(64)
object.aPottery                 = civ.getTech(65)
object.aRadio                   = civ.getTech(66)
object.aRailroad                = civ.getTech(67)
object.aRecycling               = civ.getTech(68)
object.aRefining                = civ.getTech(69)
object.aRefrigeration           = civ.getTech(70)
object.aRepublic                = civ.getTech(71)
object.aRobotics                = civ.getTech(72)
object.aRocketry                = civ.getTech(73)
object.aSanitation              = civ.getTech(74)
object.aSeafaring               = civ.getTech(75)
object.aSpaceFlight             = civ.getTech(76)
object.aStealth                 = civ.getTech(77)
object.aSteamEngine             = civ.getTech(78)
object.aSteel                   = civ.getTech(79)
object.aSuperconductor          = civ.getTech(80)
object.aTactics                 = civ.getTech(81)
object.aTheology                = civ.getTech(82)
object.aTheoryofGravity         = civ.getTech(83)
object.aTrade                   = civ.getTech(84)
object.aUniversity              = civ.getTech(85)
object.aWarriorCode             = civ.getTech(86)
object.aWheel                   = civ.getTech(87)
object.aWriting                 = civ.getTech(88)
object.aFutureTechnology        = civ.getTech(89)
object.aUserDefTechA            = civ.getTech(90)
object.aUserDefTechB            = civ.getTech(91)
object.aUserDefTechC            = civ.getTech(92)
object.aExtraAdvance1           = civ.getTech(93)
object.aExtraAdvance2           = civ.getTech(94)
object.aExtraAdvance3           = civ.getTech(95)
object.aExtraAdvance4           = civ.getTech(96)
object.aExtraAdvance5           = civ.getTech(97)
object.aExtraAdvance6           = civ.getTech(98)
object.aExtraAdvance7           = civ.getTech(99)

-- Map Locations (tiles/squares)
-- recommended key prefix 'l'

object.lTopLeft                 = civ.getTile(0,0,0)
object.lRome                    = civ.getTile(72,34,0)


-- Cities
-- recommended key prefix 'c'
-- It is not recommended to put cities into this list if the city
-- can be destroyed. This list returns an error if 'nil' is the value
-- associated with the key (see bottom of file), so that could cause
-- a problem if a city in this list is destroyed.  Also, if another
-- city is founded, the ID number of the city might get reused, causing
-- more confusion.  An alternate way to reference a city is by using
-- object.lRome.city when you actually need the city (and suitably guarding
-- against nil values)
object.cRome                    = civ.getCity(0)

-- Unit Types
-- recommended key prefix 'u'
object.uSettlers                = civ.getUnitType(0)
object.uEngineers               = civ.getUnitType(1)
object.uWarriors                = civ.getUnitType(2)
object.uPhalanx                 = civ.getUnitType(3)
object.uArchers                 = civ.getUnitType(4)
object.uLegion                  = civ.getUnitType(5)
object.uPikemen                 = civ.getUnitType(6)
object.uMusketeers              = civ.getUnitType(7)
object.uFanatics                = civ.getUnitType(8)
object.uPartisans               = civ.getUnitType(9)
object.uAlpineTroops            = civ.getUnitType(10)
object.uRiflemen                = civ.getUnitType(11)
object.uMarines                 = civ.getUnitType(12)
object.uParatroopers            = civ.getUnitType(13)
object.uMechInf                 = civ.getUnitType(14)
object.uHorsemen                = civ.getUnitType(15)
object.uChariot                 = civ.getUnitType(16)
object.uElephant                = civ.getUnitType(17)
object.uCrusaders               = civ.getUnitType(18)
object.uKnights                 = civ.getUnitType(19)
object.uDragoons                = civ.getUnitType(20)
object.uCavalry                 = civ.getUnitType(21)
object.uArmor                   = civ.getUnitType(22)
object.uCatapult                = civ.getUnitType(23)
object.uCannon                  = civ.getUnitType(24)
object.uArtillery               = civ.getUnitType(25)
object.uHowitzer                = civ.getUnitType(26)
object.uFighter                 = civ.getUnitType(27)
object.uBomber                  = civ.getUnitType(28)
object.uHelicopter              = civ.getUnitType(29)
object.uStlthFtr                = civ.getUnitType(30)
object.uStlthBmbr               = civ.getUnitType(31)
object.uTrireme                 = civ.getUnitType(32)
object.uCaravel                 = civ.getUnitType(33)
object.uGalleon                 = civ.getUnitType(34)
object.uFrigate                 = civ.getUnitType(35)
object.uIronclad                = civ.getUnitType(36)
object.uDestroyer               = civ.getUnitType(37)
object.uCruiser                 = civ.getUnitType(38)
object.uAEGISCruiser            = civ.getUnitType(39)
object.uBattleship              = civ.getUnitType(40)
object.uSubmarine               = civ.getUnitType(41)
object.uCarrier                 = civ.getUnitType(42)
object.uTransport               = civ.getUnitType(43)
object.uCruiseMsl               = civ.getUnitType(44)
object.uNuclearMsl              = civ.getUnitType(45)
object.uDiplomat                = civ.getUnitType(46)
object.uSpy                     = civ.getUnitType(47)
object.uCaravan                 = civ.getUnitType(48)
object.uFreight                 = civ.getUnitType(49)
object.uExplorer                = civ.getUnitType(50)
object.uExtraLand               = civ.getUnitType(51)
object.uExtraShip               = civ.getUnitType(52)
object.uExtraAir                = civ.getUnitType(53)
object.unotuseda                = civ.getUnitType(54)
object.unotusedb                = civ.getUnitType(55)
object.unotusedc                = civ.getUnitType(56)
object.unotusedd                = civ.getUnitType(57)
object.unotusede                = civ.getUnitType(58)
object.unotusedf                = civ.getUnitType(59)
object.unotusedg                = civ.getUnitType(60)
object.unotusedh                = civ.getUnitType(61)
object.unotusedi                = civ.getUnitType(62)
object.unotusedj                = civ.getUnitType(63)
object.unotusedk                = civ.getUnitType(64)
object.unotusedl                = civ.getUnitType(65)
object.unotusedm                = civ.getUnitType(66)
object.unotusedn                = civ.getUnitType(67)
object.unotusedo                = civ.getUnitType(68)
object.unotusedp                = civ.getUnitType(69)
object.unotusedq                = civ.getUnitType(70)
object.unotusedr                = civ.getUnitType(71)
object.unotuseds                = civ.getUnitType(72)
object.unotusedt                = civ.getUnitType(73)
object.unotusedu                = civ.getUnitType(74)
object.unotusedv                = civ.getUnitType(75)
object.unotusedw                = civ.getUnitType(76)
object.unotusedx                = civ.getUnitType(77)
object.unotusedy                = civ.getUnitType(78)
object.unotusedz                = civ.getUnitType(79)

-- City Improvements
-- recommended key prefix 'i'
--          
object.iNothing                 = civ.getImprovement(0)
object.iPalace                  = civ.getImprovement(1)
object.iBarracks                = civ.getImprovement(2)
object.iGranary                 = civ.getImprovement(3)
object.iTemple                  = civ.getImprovement(4)
object.iMarketPlace             = civ.getImprovement(5)
object.iLibrary                 = civ.getImprovement(6)
object.iCourthouse              = civ.getImprovement(7)
object.iCityWalls               = civ.getImprovement(8)
object.iAqueduct                = civ.getImprovement(9)
object.iBank                    = civ.getImprovement(10)
object.iCathedral               = civ.getImprovement(11)
object.iUniversity              = civ.getImprovement(12)
object.iMassTransit             = civ.getImprovement(13)
object.iColosseum               = civ.getImprovement(14)
object.iFactory                 = civ.getImprovement(15)
object.iManufacturingPlant      = civ.getImprovement(16)
object.iSDIDefense              = civ.getImprovement(17)
object.iRecyclingCenter         = civ.getImprovement(18)
object.iPowerPlant              = civ.getImprovement(19)
object.iHydroPlant              = civ.getImprovement(20)
object.iNuclearPlant            = civ.getImprovement(21)
object.iStockExchange           = civ.getImprovement(22)
object.iSewerSystem             = civ.getImprovement(23)
object.iSupermarket             = civ.getImprovement(24)
object.iSuperhighways           = civ.getImprovement(25)
object.iResearchLab             = civ.getImprovement(26)
object.iSAMMissileBattery       = civ.getImprovement(27)
object.iCoastalFortress         = civ.getImprovement(28)
object.iSolarPlant              = civ.getImprovement(29)
object.iHarbor                  = civ.getImprovement(30)
object.iOffshorePlatform        = civ.getImprovement(31)
object.iAirport                 = civ.getImprovement(32)
object.iPoliceStation           = civ.getImprovement(33)
object.iPortFacility            = civ.getImprovement(34)
object.iTransporter             = civ.getImprovement(35)

-- Tribes
-- recommended key prefix 't'
--
object.tBarbarians              = civ.getTribe(0)
object.tWhiteTribe              = civ.getTribe(1)
object.tGreenTribe              = civ.getTribe(2)
object.tBlueTribe               = civ.getTribe(3)
object.tYellowTribe             = civ.getTribe(4)
object.tCyanTribe               = civ.getTribe(5)
object.tOrangeTribe             = civ.getTribe(6)
object.tPurpleTribe             = civ.getTribe(7)

-- Wonders
-- recommended key prefix 'w'
object.wPyramids                = civ.getWonder(0)
object.wHangingGardens          = civ.getWonder(1)
object.wColossus                = civ.getWonder(2)
object.wLighthouse              = civ.getWonder(3)
object.wGreatLibrary            = civ.getWonder(4)
object.wOracle                  = civ.getWonder(5)
object.wGreatWall               = civ.getWonder(6)
object.wSunTzusWarAcademy       = civ.getWonder(7)
object.wKingRichardsCrusade     = civ.getWonder(8)
object.wMarcoPolosEmbassy       = civ.getWonder(9)
object.wMichelangelosChapel     = civ.getWonder(10)
object.wCopernicusObservatory   = civ.getWonder(11)
object.wMagellansExpedition     = civ.getWonder(12)
object.wShakespearesTheatre     = civ.getWonder(13)
object.wLeonardosWorkshop       = civ.getWonder(14)
object.wJSBachsCathedral        = civ.getWonder(15)
object.wIsaacNewtonsCollege     = civ.getWonder(16)
object.wAdamSmithsTradingCo     = civ.getWonder(17)
object.wDarwinsVoyage           = civ.getWonder(18)
object.wStatueofLiberty         = civ.getWonder(19)
object.wEiffelTower             = civ.getWonder(20)
object.wWomensSuffrage          = civ.getWonder(21)
object.wHooverDam               = civ.getWonder(22)
object.wManhattanProject        = civ.getWonder(23)
object.wUnitedNations           = civ.getWonder(24)
object.wApolloProgram           = civ.getWonder(25)
object.wSETIProgram             = civ.getWonder(26)
object.wCureforCancer           = civ.getWonder(27)

-- this will give you an if you try to access a key not entered into
-- the object table, which could be helpful for debugging, but it
-- means that no nil value can ever be returned for table object
-- If you need that ability, comment out this section
setmetatable(object,{__index = function(myTable,key)
    error("The object table doesn't have a value associated with "..tostring(key)..".") end})

return object
